# Generated by Django 4.1.3 on 2023-04-15 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Limit',
            fields=[
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Название ')),
                ('description', models.CharField(blank=True, max_length=150, null=True, verbose_name='Описание')),
                ('order_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Ограничение',
                'verbose_name_plural': 'Ограничения',
                'ordering': ('order_id',),
            },
        ),
    ]
