# Generated by Django 4.1.3 on 2023-04-17 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('limits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='limit',
            name='name',
            field=models.CharField(default=1, max_length=150, verbose_name='Название '),
            preserve_default=False,
        ),
    ]
