# Generated by Django 4.1.3 on 2023-09-26 00:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advert',
            options={
                'ordering': ['-pub_date', '-id'],
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявления',
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={
                'ordering': ['name'],
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.AlterModelOptions(
            name='city',
            options={
                'ordering': ['name'],
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.AlterField(
            model_name='advert',
            name='pub_date',
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                null=True,
                verbose_name='Дата публикации',
            ),
        ),
        migrations.AlterField(
            model_name='advert',
            name='title',
            field=models.CharField(
                db_index=True, max_length=128, verbose_name='Заголовок'
            ),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Название'),
        ),
    ]
