# Generated by Django 4.1.3 on 2023-09-26 01:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0002_alter_advert_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'Город', 'verbose_name_plural': 'Города'},
        ),
    ]
