# Generated by Django 4.1.3 on 2023-09-26 08:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0003_alter_category_options_alter_city_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advert',
            options={
                'ordering': ['-pub_date', 'id'],
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявления',
            },
        ),
    ]
