# Generated by Django 4.1.3 on 2023-09-26 09:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0004_alter_advert_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advert',
            options={
                'ordering': ['id'],
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявления',
            },
        ),
    ]
