# Generated by Django 4.1.3 on 2023-04-15 11:46

import abonents.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('limits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abonent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='Не более 150 символов. Только буквы, цифры и @/./+/-/_/ /.', max_length=150, unique=True, validators=[abonents.models.CustomUsernameValidator()], verbose_name='ФИО')),
                ('phone', models.IntegerField(error_messages={'unique': 'Пользователь с указанным номером уже существует.'}, help_text='Должен только содержать 4 цифры.', unique=True, validators=[abonents.models.PhoneValidator()], verbose_name='Телефонный номер')),
                ('limit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abonents', to='limits.limit', verbose_name='Ограничения')),
            ],
            options={
                'verbose_name': 'Абонент',
                'verbose_name_plural': 'Абоненты',
                'ordering': ('id',),
            },
        ),
    ]
