# Generated by Django 3.2.19 on 2023-06-14 12:39

from django.db import migrations, models

import my_tests.models


class Migration(migrations.Migration):

    dependencies = [
        ('my_tests', '0002_alter_uniquelogin_unique_string'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uniquelogin',
            name='unique_string',
            field=models.CharField(default=my_tests.models.generate_unique_string, max_length=10, unique=True),
        ),
    ]
