# Generated by Django 4.1.3 on 2023-10-14 16:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('city', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={
                'ordering': ['name'],
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
    ]
