# Generated by Django 4.1.3 on 2023-10-18 19:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('city', '0003_alter_city_latitude_alter_city_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(
                db_index=True,
                max_length=100,
                unique=True,
                verbose_name='Название',
            ),
        ),
    ]
