# Generated by Django 4.1.3 on 2023-10-18 20:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('city', '0004_alter_city_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(
                db_index=True, max_length=100, verbose_name='Название'
            ),
        ),
        migrations.AddConstraint(
            model_name='city',
            constraint=models.UniqueConstraint(
                fields=('name', 'latitude', 'longitude'), name='unique_city'
            ),
        ),
    ]
